import Link from "next/link";
import type { Faq } from "@/lib/content/types";

export const compressPanelFaq: Faq = { question: "Does this make a lossless image?", answer: "No. The output is JPEG, so quality can change and PNG transparency is not preserved." };
export const convertPanelFaq: Faq = { question: "Which format should I choose?", answer: "Use PNG when transparency matters, JPEG for broadly supported photographic output, and WebP when a newer image format is suitable for your workflow." };
export const imagesToPdfPanelFaq: Faq = { question: "Can I make a photo PDF with several pictures?", answer: "Yes. Each selected image becomes its own page, and the list can be reordered before generation." };
export const pdfToImagesPanelFaq: Faq = { question: "Can I download every page together?", answer: "Yes. After rendering, use Download all ZIP for one archive, or download pages individually." };
export const resizePanelFaq: Faq = { question: "Does resizing change the aspect ratio?", answer: "Only if you unlock the ratio and enter a width and height that do not match the original. With the lock on, both sides scale together so nothing is stretched." };
export const mergePdfPanelFaq: Faq = { question: "Can I merge PDFs with different page sizes?", answer: "Yes. Each page keeps its own size, so A4, Letter, and scanned pages can sit in the same document without being resized." };
export const splitPdfPanelFaq: Faq = { question: "Can I split out pages that are not next to each other?", answer: "Yes. Select any combination of pages, or enter a range such as 1-3, 7, 12-14, and only those pages are saved." };
export const compressPdfPanelFaq: Faq = { question: "Can I undo a compression?", answer: "The original file is never changed. Keep it, and re-run the tool with the Light level if you want a gentler result." };
export const rotatePdfPanelFaq: Faq = { question: "Can I rotate pages in opposite directions?", answer: "Yes. Turn pages one at a time in either direction, then save once. Each page keeps the angle it was given." };

function PanelFaq({ faq }: { faq: Faq }) {
  return <details><summary>{faq.question}</summary><p>{faq.answer}</p></details>;
}

function ToolLinks({ links }: { links: Array<[string, string]> }) {
  return <p className="tool-links">Related tools: {links.map(([href, label], index) => <span key={href}><Link href={href}>{label}</Link>{index < links.length - 1 ? " · " : ""}</span>)}</p>;
}

export function CompressSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="compress-guide"><h2 id="compress-guide">Reduce an image to a custom file size</h2><p>Enter 200 KB, another KB value, or a limit in MB. Filekind searches for a JPEG output at or below that maximum; it does not promise an exactly matching size. This is useful when a photo needs to fit below an upload limit.</p><ol><li>Choose a JPEG or PNG image up to 25 MB.</li><li>Enter the maximum size and choose KB or MB, or use the 200 KB preset.</li><li>Generate the compressed JPEG, then compare its size and dimensions before downloading.</li></ol><p>Compression can lower JPEG quality and reduce pixel dimensions when needed. PNG transparency becomes white. File size is the amount of stored data, while dimensions are the image width and height; reducing one does not always reduce the other.</p><PanelFaq faq={compressPanelFaq} /><ToolLinks links={[["/convert-image", "convert the result to PNG or WebP"], ["/images-to-pdf", "put images into a PDF"]]} /></section>;
}

export function ConvertSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="convert-guide"><h2 id="convert-guide">Convert between JPG, PNG, and WebP</h2><p>All six distinct pairs work here: JPG to PNG, PNG to JPG, WebP to JPG, JPG to WebP, PNG to WebP, and WebP to PNG. JPG and JPEG are the same image format. PNG supports transparency; JPEG does not.</p><ol><li>Choose one JPEG, PNG, or static WebP image up to 25 MB.</li><li>Select the output format.</li><li>Generate and download the new file.</li></ol><p>Animated WebP files are rejected rather than silently losing their animation. Converting a JPEG to PNG changes the container but cannot restore detail already lost in the JPEG.</p><PanelFaq faq={convertPanelFaq} /><ToolLinks links={[["/compress-image", "compress a JPEG or PNG"], ["/images-to-pdf", "combine images into a PDF"]]} /></section>;
}

export function ImagesToPdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="images-pdf-guide"><h2 id="images-pdf-guide">Combine photos into one PDF</h2><p>Add JPG, PNG, static WebP, or HEIC images, arrange their order, and create one PDF with one image per page. The default is Fit page, no margins, and automatic orientation, which follows the image shape.</p><ol><li>Select one or more images, up to 25 MB each.</li><li>Drag images into the order you want.</li><li>Choose Fit, A4, or Letter, then set orientation or an optional custom margin.</li><li>Create the PDF and download it.</li></ol><p>Fit uses a page sized around each image. A4 and Letter place each image within the selected paper size. This tool creates pages from images; it does not add OCR or searchable text, and the text and artwork inside a page are never edited.</p><PanelFaq faq={imagesToPdfPanelFaq} /><ToolLinks links={[["/compress-image", "reduce image file sizes first"], ["/compress-pdf", "shrink the finished document later"], ["/pdf-to-images", "render PDF pages as images"]]} /></section>;
}

export function PdfToImagesSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="pdf-images-guide"><h2 id="pdf-images-guide">Save complete PDF pages as pictures</h2><p>This tool renders each full PDF page to a JPG or PNG image. It does not extract individual embedded pictures from inside a page.</p><ol><li>Choose a PDF up to 50 MB.</li><li>Select JPG or PNG.</li><li>Render the pages, then download one page or all pages as a ZIP.</li></ol><p>The current limits are 100 pages, 120 million rendered pixels, and 150 MB of total output. Password-protected PDFs are not supported. The page render is created locally in your browser.</p><PanelFaq faq={pdfToImagesPanelFaq} /><ToolLinks links={[["/images-to-pdf", "create a PDF from images"], ["/convert-image", "convert image formats"]]} /></section>;
}

export function ResizeSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="resize-guide"><h2 id="resize-guide">Change image dimensions without uploading</h2><p>Resizing sets the width and height in pixels, which changes how large the picture appears and how much data it stores. Enter exact pixels for a required size, or a percentage when you only want the image smaller.</p><ol><li>Choose a JPEG, PNG, or static WebP image up to 25 MB.</li><li>Set a percentage, or enter a width and height with the aspect ratio locked.</li><li>Pick JPG or PNG output and adjust the JPEG quality when needed.</li><li>Generate, compare the before and after size, then download.</li></ol><p>Making an image smaller reduces file size, while enlarging it adds pixels without adding detail. The browser scales the pixels locally, so the original file stays on your device. PNG output stays lossless; JPG output trades a little quality for a much smaller file.</p><PanelFaq faq={resizePanelFaq} /><ToolLinks links={[["/compress-image", "reduce the file size further"], ["/convert-image", "convert the resized image to another format"]]} /></section>;
}

export function MergePdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="merge-pdf-guide"><h2 id="merge-pdf-guide">Combine documents without uploading them</h2><p>Filekind joins PDF files by copying their pages into one new document, so the finished file keeps the text, links, and images of the originals. The list order is the page order: the top file comes first.</p><ol><li>Choose up to 20 PDF files, each up to 50 MB.</li><li>Drag them into the order you need, and remove any you do not want.</li><li>Merge, then check the page count and size before downloading.</li></ol><p>The finished document must stay within 100 pages, which matches the limit used by the rest of the site. Fields, bookmarks, and file attachments from the source documents are not carried across, and password-protected PDFs have to be unlocked first.</p><PanelFaq faq={mergePdfPanelFaq} /><ToolLinks links={[["/split-pdf", "split the result back apart"], ["/compress-pdf", "make the merged file smaller"], ["/pdf-to-images", "turn pages into pictures"]]} /></section>;
}

export function SplitPdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="split-pdf-guide"><h2 id="split-pdf-guide">Take the pages you need from a document</h2><p>Page previews are rendered in your browser, so you can see what you are selecting before anything is created. Click individual pages, type a range such as 2-4, 9, or clear the selection and start again.</p><ol><li>Open a PDF up to 50 MB and 100 pages.</li><li>Select pages with the previews or a typed range.</li><li>Choose one combined PDF, or one file per page in a ZIP.</li><li>Generate and download the result.</li></ol><p>Pages are copied rather than re-rendered, so quality does not change and text stays selectable. This tool does not delete pages from the original file, and it cannot open password-protected documents.</p><PanelFaq faq={splitPdfPanelFaq} /><ToolLinks links={[["/merge-pdf", "combine PDFs into one file"], ["/rotate-pdf", "turn pages before splitting"], ["/pdf-to-images", "save pages as images"]]} /></section>;
}

export function CompressPdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="compress-pdf-guide"><h2 id="compress-pdf-guide">Shrink a PDF by rebuilding its images</h2><p>Most of the weight in a scan or a photo-heavy PDF comes from the pictures. This tool re-encodes those embedded images at the level you choose, and the strong level also rebuilds large images at a smaller size, while the text streams are copied untouched.</p><ol><li>Choose a PDF up to 50 MB and 100 pages.</li><li>Pick Light, Medium, or Strong depending on how much you need to save.</li><li>Compress and compare the before and after sizes.</li><li>Download the smaller document.</li></ol><p>Because text and links are never rasterised, the result can still be selected, searched, and copied. Vector drawings and fonts are already compact, so a text-only PDF will barely change. The original file is never modified.</p><PanelFaq faq={compressPdfPanelFaq} /><ToolLinks links={[["/compress-image", "compress a photo before building a PDF"], ["/images-to-pdf", "build a smaller PDF from images"], ["/pdf-to-images", "check what a page looks like"]]} /></section>;
}

export function RotatePdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="rotate-pdf-guide"><h2 id="rotate-pdf-guide">Turn pages so the document reads correctly</h2><p>A PDF that opens sideways is awkward to read on a phone and awkward to print. Set the angle per page or for the whole file, watch the preview update, and save once when everything looks right.</p><ol><li>Open a PDF up to 50 MB and 100 pages.</li><li>Turn individual pages left or right, or rotate the whole document.</li><li>Save the file and check it in your PDF reader.</li></ol><p>Only the page rotation value changes, so nothing is re-encoded and there is no quality loss. Angles already present in the source file are preserved and added to, which makes it easy to correct a scanned page that is already at 90 degrees.</p><PanelFaq faq={rotatePdfPanelFaq} /><ToolLinks links={[["/split-pdf", "keep only the pages you turned"], ["/merge-pdf", "combine the result with other files"], ["/pdf-to-images", "render pages as pictures"]]} /></section>;
}
