import Link from "next/link";

function ToolLinks({ links }: { links: Array<[string, string]> }) {
  return <p className="tool-links">Related tools: {links.map(([href, label], index) => <span key={href}><Link href={href}>{label}</Link>{index < links.length - 1 ? " · " : ""}</span>)}</p>;
}

export function CompressSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="compress-guide"><h2 id="compress-guide">Reduce an image to a custom file size</h2><p>Enter 200 KB, another KB value, or a limit in MB. Filekind searches for a JPEG output at or below that maximum; it does not promise an exactly matching size. This is useful when a photo needs to fit below an upload limit.</p><ol><li>Choose a JPEG or PNG image up to 25 MB.</li><li>Enter the maximum size and choose KB or MB, or use the 200 KB preset.</li><li>Generate the compressed JPEG, then compare its size and dimensions before downloading.</li></ol><p>Compression can lower JPEG quality and reduce pixel dimensions when needed. PNG transparency becomes white. File size is the amount of stored data, while dimensions are the image width and height; reducing one does not always reduce the other.</p><details><summary>Does this make a lossless image?</summary><p>No. The output is JPEG, so quality can change and PNG transparency is not preserved.</p></details><ToolLinks links={[["/convert-image", "convert the result to PNG or WebP"], ["/images-to-pdf", "put images into a PDF"]]} /></section>;
}

export function ConvertSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="convert-guide"><h2 id="convert-guide">Convert between JPG, PNG, and WebP</h2><p>All six distinct pairs work here: JPG to PNG, PNG to JPG, WebP to JPG, JPG to WebP, PNG to WebP, and WebP to PNG. JPG and JPEG are the same image format. PNG supports transparency; JPEG does not.</p><ol><li>Choose one JPEG, PNG, or static WebP image up to 25 MB.</li><li>Select the output format.</li><li>Generate and download the new file.</li></ol><p>Animated WebP files are rejected rather than silently losing their animation. Converting a JPEG to PNG changes the container but cannot restore detail already lost in the JPEG.</p><details><summary>Which format should I choose?</summary><p>Use PNG when transparency matters, JPEG for broadly supported photographic output, and WebP when a newer image format is suitable for your workflow.</p></details><ToolLinks links={[["/compress-image", "compress a JPEG or PNG"], ["/images-to-pdf", "combine images into a PDF"]]} /></section>;
}

export function ImagesToPdfSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="images-pdf-guide"><h2 id="images-pdf-guide">Combine photos into one PDF</h2><p>Add JPG, PNG, or static WebP images, arrange their order, and create one PDF with one image per page. The default is Fit page, no margins, and automatic orientation, which follows the image shape.</p><ol><li>Select one or more images, up to 25 MB each.</li><li>Drag images into the order you want.</li><li>Choose Fit, A4, or Letter, then set orientation or an optional custom margin.</li><li>Create the PDF and download it.</li></ol><p>Fit uses a page sized around each image. A4 and Letter place each image within the selected paper size. This tool creates pages from images; it does not add OCR, searchable text, PDF editing, or a separate PDF compression feature.</p><details><summary>Can I make a photo PDF with several pictures?</summary><p>Yes. Each selected image becomes its own page, and the list can be reordered before generation.</p></details><ToolLinks links={[["/compress-image", "reduce image file sizes first"], ["/pdf-to-images", "render PDF pages as images"]]} /></section>;
}

export function PdfToImagesSeoContent() {
  return <section className="info-panel seo-content" aria-labelledby="pdf-images-guide"><h2 id="pdf-images-guide">Save complete PDF pages as pictures</h2><p>This tool renders each full PDF page to a JPG or PNG image. It does not extract individual embedded pictures from inside a page.</p><ol><li>Choose a PDF up to 50 MB.</li><li>Select JPG or PNG.</li><li>Render the pages, then download one page or all pages as a ZIP.</li></ol><p>The current limits are 100 pages, 120 million rendered pixels, and 150 MB of total output. Password-protected PDFs are not supported. The page render is created locally in your browser.</p><details><summary>Can I download every page together?</summary><p>Yes. After rendering, use Download all ZIP for one archive, or download pages individually.</p></details><ToolLinks links={[["/images-to-pdf", "create a PDF from images"], ["/convert-image", "convert image formats"]]} /></section>;
}
