name = "filekind-analytics"
main = "src/index.ts"
compatibility_date = "2026-09-15"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://filekind.com,https://www.filekind.com,https://filekind.muhammadhassangul01.workers.dev,https://filekind.pages.dev,http://localhost:3000"

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "filekind-analytics"
database_id = "c8e5618c-b5f1-46f4-8573-dcc1fc1b562d"
migrations_dir = "migrations"
